# Generated by Django 5.2.15 on 2026-07-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClauseRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(choices=[('confidentiality', 'Confidentiality'), ('payment_terms', 'Payment Terms'), ('termination', 'Termination Conditions'), ('liability', 'Liability'), ('indemnification', 'Indemnification'), ('dispute_resolution', 'Dispute Resolution'), ('force_majeure', 'Force Majeure'), ('intellectual_property', 'Intellectual Property'), ('warranty', 'Warranty'), ('data_privacy', 'Data Privacy')], max_length=50)),
                ('keyword', models.CharField(max_length=200)),
                ('risk_level_if_missing', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='high', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
