# Generated by Django 5.2.15 on 2026-07-02 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_clauserule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(choices=[('confidentiality', 'Confidentiality'), ('payment_terms', 'Payment Terms'), ('termination', 'Termination Conditions'), ('liability', 'Liability'), ('indemnification', 'Indemnification'), ('dispute_resolution', 'Dispute Resolution'), ('force_majeure', 'Force Majeure'), ('intellectual_property', 'Intellectual Property'), ('warranty', 'Warranty'), ('data_privacy', 'Data Privacy')], max_length=50)),
                ('is_present', models.BooleanField(default=False)),
                ('clause_text', models.TextField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('risk_reason', models.TextField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='myapp.contract')),
            ],
        ),
    ]
