# Generated by Django 5.2.15 on 2026-07-02 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contractclause'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_risk_score', models.FloatField(default=0)),
                ('overall_risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('total_clauses_detected', models.IntegerField(default=0)),
                ('missing_clauses_count', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_report', to='myapp.contract')),
            ],
        ),
    ]
