# Generated by Django 5.2.15 on 2026-07-02 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_riskreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MissingClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(choices=[('confidentiality', 'Confidentiality'), ('payment_terms', 'Payment Terms'), ('termination', 'Termination Conditions'), ('liability', 'Liability'), ('indemnification', 'Indemnification'), ('dispute_resolution', 'Dispute Resolution'), ('force_majeure', 'Force Majeure'), ('intellectual_property', 'Intellectual Property'), ('warranty', 'Warranty'), ('data_privacy', 'Data Privacy')], max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='high', max_length=10)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_clauses', to='myapp.contract')),
            ],
        ),
    ]
