# Generated by Django 5.2.15 on 2026-07-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_notification_chatmessage_complaint_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clauserule',
            name='clause_type',
            field=models.CharField(help_text="Name of this clause type, defined by the admin (e.g. 'Confidentiality', 'Data Privacy'). Free text — not restricted to a predefined list.", max_length=100),
        ),
        migrations.AlterField(
            model_name='clauserule',
            name='keyword',
            field=models.CharField(help_text="Comma-separated list of keywords/phrases, e.g. 'confidentiality, non-disclosure, nda, trade secret'. The clause is considered present if ANY term matches.", max_length=500),
        ),
        migrations.AlterField(
            model_name='contractclause',
            name='clause_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='missingclause',
            name='clause_type',
            field=models.CharField(max_length=100),
        ),
    ]
